# This is a basic workflow to help you get started with Actions

name: Call Server API

# Controls when the workflow will run
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
    # Allow this workflow to be run on-demand

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl -s https://chat-app-apis-ch3l.onrender.com
